AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: z2c-fce-deploy
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Application
          Value: z2c-fce
