AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiPathStudyReminder:
    Type: String
    Default: studyreminder
  StageName:
    Type: String
    Default: live
  TwilioAuthToken:
    Type: String
  TwilioAccountSid:
    Type: String

Resources:
  StudyReminderFormAPI:
    Type: AWS::Serverless::Api
    Description: API for sending study reminder emails
    Properties:
      BinaryMediaTypes: 
        - "application/json"
      Cors:
        AllowMethods: "'POST'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'" # TODO: lock this down
        MaxAge: "'600'"
        AllowCredentials: False
      # TODO: Add OpenAPI definition files 
      # DefinitionBody: String
      # DefinitionUri: String | ApiDefinition
      EndpointConfiguration: 
        Type: EDGE
      Models:
        StudyReminderFormInformation:
          type: object
          required:
            - email_address
            - subject
            - body
          properties:
            email_address:
              type: string
            subject:
              type: string
            integer:
              type: string
      Name: StudyReminderFormAPI
      OpenApiVersion: "3.0.1"
      StageName: !Ref StageName
      Tags: 
        ApplicationName: StudyReminderForm 
      TracingEnabled: False

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref StudyReminderFormAPI
      ParentId: !GetAtt 
        - StudyReminderFormAPI
        - RootResourceId
      PathPart: api

  V1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref StudyReminderFormAPI
      ParentId: !Ref ApiResource
      PathPart: v1
  
  StudyReminderRootStudyReminderResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref StudyReminderFormAPI
      ParentId: !Ref V1Resource
      PathPart: !Ref ApiPathStudyReminder
  
  LambdaPOSTPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt StudyReminderFormLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        !Join ["", [
          "arn:aws:execute-api:", 
          !Ref "AWS::Region", 
          ":", 
          !Ref "AWS::AccountId",
          ":",
          !Ref StudyReminderFormAPI,
          "/*/POST/api/v1/",
          !Ref ApiPathStudyReminder
          ]
        ]
  
  ApiDeployment202103212022:
    DependsOn: StudyReminderPOSTMethod
    Type: AWS::ApiGateway::Deployment
    Properties: 
      Description: deployment of courses endpoints
      RestApiId: !Ref StudyReminderFormAPI
      StageName: !Ref StageName

  StudyReminderPOSTMethod:
    DependsOn: LambdaPOSTPermission
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref StudyReminderRootStudyReminderResource
      RestApiId: !Ref StudyReminderFormAPI
      AuthorizationType: NONE
      HttpMethod: POST
      ApiKeyRequired: false
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ["", [
          "arn:aws:apigateway:",
          !Ref "AWS::Region",
          ":lambda:path/2015-03-31/functions/",
          !GetAtt StudyReminderFormLambda.Arn,
          "/invocations"
        ]]

  StudyReminderFormLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StudyReminderFormLambdaRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
                - "apigateway.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  StudyReminderFormLambda:
    Type: AWS::Serverless::Function
    Description: description
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 30
      FunctionName: StudyReminderFormFunction
      MemorySize: 128
      Role: !GetAtt StudyReminderFormLambdaRole.Arn
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
      Events:
        StudyReminderEvent:
          Type: Api
          Properties:
            Method: POST
            Path: "/studyreminder"
            RestApiId: !Ref StudyReminderFormAPI
      Tags:
        ApplicationName: StudyReminderForm

  Authorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      AuthorizerCredentials: !GetAtt 
        - StudyReminderFormLambdaRole
        - Arn
      AuthorizerResultTtlInSeconds: 300
      AuthorizerUri: !Join 
        - ''
        - - 'arn:aws:apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt 
            - StudyReminderFormLambda
            - Arn
          - /invocations
      Type: TOKEN
      IdentitySource: method.request.header.Auth
      Name: DefaultAuthorizer
      RestApiId: !Ref StudyReminderFormAPI
  
  StudentInformationTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Z2C-FCE-Students"
      AttributeDefinitions: 
        - AttributeName: "phoneNumber"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification: 
        Enabled: false
      KeySchema: 
        - AttributeName: "phoneNumber"
          KeyType: HASH
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: false
      TableClass: "STANDARD"
      Tags: 
        - Key: Application
          Value: Z2C-FCE